from __future__ import annotations

import uuid
from datetime import datetime, timedelta, timezone
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID
from .db import connect
from .crypto import seal
from .audit import audit, now

def issue_certificate(subject: str, days: int, actor: str, rotated_from: str | None = None):
    key = rsa.generate_private_key(public_exponent=65537, key_size=3072)
    current = datetime.now(timezone.utc); before = current - timedelta(minutes=1); after = current + timedelta(days=days)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, subject)])
    cert = x509.CertificateBuilder().subject_name(name).issuer_name(name).public_key(key.public_key()).serial_number(x509.random_serial_number()).not_valid_before(before).not_valid_after(after).add_extension(x509.BasicConstraints(ca=False, path_length=None), True).sign(key, hashes.SHA256())
    pem = cert.public_bytes(serialization.Encoding.PEM).decode(); private = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8, serialization.NoEncryption())
    kid, cid = str(uuid.uuid4()), str(uuid.uuid4())
    with connect() as conn:
        conn.execute("INSERT INTO keys VALUES(?,?,?,?,?,?,?,?,?,?)", (kid,"certificate","RSA-3072",cert.public_key().public_bytes(serialization.Encoding.DER,serialization.PublicFormat.SubjectPublicKeyInfo),seal(private),"active",now(),None,None,None))
        conn.execute("INSERT INTO certificates VALUES(?,?,?,?,?,?,?,?,?,?,?,?)", (cid,kid,subject,str(cert.serial_number),pem,before.isoformat(),after.isoformat(),"active",now(),rotated_from,None))
    audit("certificate_issued", actor, cid, {"subject": subject, "not_after": after.isoformat()})
    return {"certificate_id": cid, "key_id": kid, "subject": subject, "serial_number": str(cert.serial_number), "not_after": after.isoformat(), "pem": pem, "pqc_note": "RSA certificate; not a PQC certificate"}

def list_certificates():
    with connect() as conn: rows = conn.execute("SELECT id,key_id,subject,serial_number,not_before,not_after,state,created_at,rotated_from,revoked_at FROM certificates ORDER BY created_at DESC").fetchall()
    threshold = datetime.now(timezone.utc) + timedelta(days=30)
    return [{**dict(row), "rotation_due": row["state"] == "active" and datetime.fromisoformat(row["not_after"]) <= threshold} for row in rows]

def rotate_certificate(cert_id: str, actor: str):
    with connect() as conn: row = conn.execute("SELECT subject,key_id,state FROM certificates WHERE id=?", (cert_id,)).fetchone()
    if not row or row["state"] != "active": raise ValueError("Active certificate not found")
    replacement = issue_certificate(row["subject"], 365, actor, cert_id)
    with connect() as conn:
        conn.execute("UPDATE certificates SET state='rotated' WHERE id=?", (cert_id,)); conn.execute("UPDATE keys SET state='retired',rotated_at=? WHERE id=?", (now(),row["key_id"]))
    return replacement

def revoke_certificate(cert_id: str, actor: str):
    with connect() as conn: row = conn.execute("SELECT key_id FROM certificates WHERE id=?", (cert_id,)).fetchone()
    if not row: raise ValueError("Certificate not found")
    with connect() as conn:
        conn.execute("UPDATE certificates SET state='revoked',revoked_at=? WHERE id=?", (now(),cert_id)); conn.execute("UPDATE keys SET state='revoked',revoked_at=? WHERE id=?", (now(),row["key_id"]))
    audit("certificate_revoked", actor, cert_id, {}); return {"certificate_id": cert_id, "state": "revoked"}

def build_crl():
    # A PEM CRL requires a CA signing key. This endpoint returns a clearly marked
    # development CRL generated by a process-local CA key; replace with a durable CA/HSM in production.
    ca = rsa.generate_private_key(public_exponent=65537, key_size=2048); name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "POST-QUANTAM Dev CA")]); now_dt = datetime.now(timezone.utc)
    builder = x509.CertificateRevocationListBuilder().issuer_name(name).last_update(now_dt).next_update(now_dt + timedelta(days=1))
    with connect() as conn: rows = conn.execute("SELECT serial_number,revoked_at FROM certificates WHERE state='revoked'").fetchall()
    for row in rows:
        builder = builder.add_revoked_certificate(x509.RevokedCertificateBuilder().serial_number(int(row[0])).revocation_date(datetime.fromisoformat(row[1])).build())
    return builder.sign(ca, hashes.SHA256()).public_bytes(serialization.Encoding.PEM).decode()
